name: Roxus CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Roxus
      uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install Build Tools
      run: sudo apt-get install tup clang lld
    - name: Build Roxus
      run: tup init && tup
    - name: Upload Roxus
      uses: actions/upload-artifact@v4
      with:
        name: Roxus Build
        path: ./root/
